#!/usr/bin/env python

# Author: Tanay Agarwal (tagarwa2)

import optparse
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--num_iterations", dest="num_iters", default=10, type="int", help="Number of iterations to run EM (default=10)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("Training with IBM Model 1............\n")
# IBM Model 1 pseudocode obtained from http://mt-class.org/jhu/slides/lecture-ibm-model1.pdf

bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))[:opts.num_sents]]
t_fe = {}
for (n, (f, e)) in enumerate(bitext):
  for f_i in set(f):
    for e_j in set(e):
      t_fe[(f_i, e_j)] = 0.25 # uniform initialization

for iteration in range(0, opts.num_iters):
  sys.stderr.write("Iteration " + str(iteration) + "\n")
  sys.stderr.write("Initializing counts\n")
  # initialize counts and totals
  count_fe = {}
  total_e = {}
  for (f_i, e_j) in t_fe.keys():
    count_fe[(f_i, e_j)] = 0
    total_e[e_j] = 0

  for (n, (f, e)) in enumerate(bitext):
    # sys.stderr.write("Sentence " + str(n) + "\n")
    # compute normalization
    s_total = {}
    for f_i in set(f):
      s_total[f_i] = 0
      for e_j in set(e):
        s_total[f_i] += t_fe[(f_i, e_j)]

    # collect counts
    for f_i in set(f):
      for e_j in set(e):
        count_fe[(f_i, e_j)] += ( t_fe[(f_i, e_j)] / s_total[f_i] )
        total_e[e_j] += ( t_fe[(f_i, e_j)] / s_total[f_i] )

  # estimate probabilities
  sys.stderr.write("Estimating probabilities\n")
  for (f_i, e_j) in t_fe.keys():
    t_fe[(f_i, e_j)] = count_fe[(f_i, e_j)] / total_e[e_j]

sys.stderr.write("Generating alignments...........\n")
# generate optimal alignments
for (f, e) in bitext:
  for (i, f_i) in enumerate(f): 
    best_prob = 0
    best_j = 0
    for (j, e_j) in enumerate(e):
      if t_fe[(f_i, e_j)] > best_prob:
        best_prob = t_fe[(f_i, e_j)]
        best_j = j
    sys.stdout.write("%i-%i " % (i, best_j))
  sys.stdout.write("\n")
